### PR TITLE
Finish the filtering function

### PR DESCRIPTION
**Pull request by tutingjun**
Finish the filtering of multiple tours 
- make sure only one request is fired to database per load
- if in default mode with multiple tours, each tour has its own color and numbering

Things to fix:
- The color of each tour is completely randomized, meaning that on each refresh the color will change. Do we want a defined color for each tour
- The marker icon is completely built on css so it can be changed easily
- clustering of the items not implemented
- A loading screen on the map before all the paths are rendered?

### CODE REVIEW

**Comment by apjmason** [comment]
Making progress! This is looking much better.

On the colors, yes, I think having a defined color for each tour makes sense. I propose using [this scheme from colorbrewer](https://colorbrewer2.org/?type=qualitative&scheme=Paired&n=10) as defaults for the first 10 tours. 

`['#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a']`

Long term, it would be great to store those values in the tour table db and add them as an editable value on the Tour edit forms so people can customize.

**Comment by apjmason** [comment]
It would also be good to add a legend (down the line) a la this example: https://codepen.io/haakseth/pen/KQbjdO

**Comment by apjmason** [comment]
It does take a long time to load so a loading screen would be good. Easiest would be to just remove the first time check from the existing overlay help text, and add more detail there on how to use it.

**Comment by tutingjun** [comment]
Is it possible to add a field in tour admin side for the color and we can access it directly from the backend. On the top of my head, I don't see a easy solution to map the color to the tour definitively each time

**Comment by apjmason** [comment]
> > It does take a long time to load so a loading screen would be good. Easiest would be to just remove the first time check from the existing overlay help text, and add more detail there on how to use it.
> 
> I am a bit confused about the first time check from existing overlay help text. 🫢

https://github.com/DigitalCarleton/MallMap/blob/fa5e2c8799f9f3cd05ff493fe8a97c2e69fd1e17/views/public/javascripts/mall-map.js#L54

**Comment by apjmason** [comment]
> Is it possible to add a field in tour admin side for the color and we can access it directly from the backend. On the top of my head, I don't see a easy solution to map the color to the tour definitively each time

Yes, this is possible. We would add it to the tours/edit form and then pull it from the tours db

**Review by apjmason — APPROVED** [review]

**Comment by apjmason** [comment]
Approving and merging because #20 contains further fixes.

**Pull request merged**
